# Generated by Django 4.1.6 on 2023-02-06 10:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_of_work',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
