# Generated by Django 4.1.6 on 2023-02-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_country_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='country_of_work',
            new_name='country',
        ),
    ]
