# Generated by Django 4.1.6 on 2023-02-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_country_of_work_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
